### ISSUE TITLE
Minor typo page 70 in book and online resource

### ISSUE THREAD

**Issue by ngiann** [jmzobitz/ModelingWithR#9]
Last sentence of page 70:
"Next we apply local linearization to construct a locally linear approximation **to** L(y) **to** f(y) at y=*y:"

Perhaps the first "to" is not needed.

**Comment by jmzobitz** [comment]
Fixed in html version and in running google doc of textbook errata: [LINK](https://docs.google.com/document/d/1BJmyeQbrDRmUdoM11pZTA_kTV0XG76L1UQLOxCIR8M0/edit?usp=sharing)
